=== washingtonpost/ad-schema/schema/ad-insertion_operation.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/ad-insertion_operation.json",
	"description": "The return value of an operation that performs a dynamic ad insertion into a product",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"_id": {
			"$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.6.2/traits/trait_id.json"
		},
		"product": {
			"type": "object",
			"_id": {
				"$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.6.2/traits/trait_id.json"
			},
			"adSlotsAvailable": {
				"type": "array",
				"items": {
					"$ref": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/traits/slot.json"
				}
			}
		},
		"slotsTargeted": {
			"type": "array",
			"items": {
				"$ref": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/traits/slot.json"
			}
		},
		"operations": {
			"type": "array",
			"items": {
				"$ref": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/traits/adOperationResult.json"
			}
		}
	}
}

=== washingtonpost/ad-schema/examples/inserted-operation.json
{
	"_id": "adEntry5",
	"product": {
		"type": "object",
		"_id": "aProductName",
		"adSlotsAvailable": [
			{
				"_id": "audioPreroll",
				"name": "Audio Preroll",
				"size": "30s",
				"priority": 2
			},
			{
				"_id": "audioPostroll",
				"name": "Audio Post",
				"size": "30s",
				"priority": 5
			}
		]
	},
	"slotsTargeted": [
		{
			"_id": "audioPreroll",
			"name": "Audio Preroll",
			"size": "30s",
			"priority": 2
		}
	],
	"operations": [
		{
			"type": "audio",
			"operation": "insert",
			"date": "1529696474539",
			"organization_id": "WashPost",
			"results": [
				{
					"_id": "operation123",
					"target": "podcastShowX",
					"asset": "123assetId",
					"status": true,
					"fileWithAds": "http://yoursite.com/with-ads/file.mp3",
					"fileWithoutAds": "http://yoursite.com/without-ads/file.mp3",
					"localFileWithAds": "./files/file.mp3",
					"distribution": [
						"any"
					],
					"slots": [
						{
							"_id": "audioPreroll",
							"name": "Audio Preroll",
							"size": "30s",
							"priority": 2
						}
					]
				}
			]
		}
	]
}
