=== washingtonpost/ad-schema/schema/ad-targeting_operation.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/ad-targeting_operation.json",
	"description": "Ad without ID to push targeting to an ad controller",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"version": {
			"$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.6.2/traits/trait_version.json"
		},
		"adServerConfig": {
			"$ref": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/traits/adServerConfig.json"
		},
		"creatives": {
			"type": "array",
			"items": {
				"$ref": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/creative.json"
			}
		},
		"template": {
			"$ref": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/traits/template.json"
		},
		"campaign": {
			"type": "object",
			"properties": {
				"targeting": {
					"$ref": "https://raw.githubusercontent.com/washingtonpost/ad-schema/master/schema/targeting.json"
				}
			}
		}
	}
}

=== washingtonpost/ad-schema/examples/targeting-operation.json
{
	"version": "0.6.2",
	"adServerConfig": {
		"lineItemID": "123lineItemID",
		"campaignID": "123campaignID",
		"creativeID": "123creativeID"
	},
	"creatives": [
		{
			"_id": "123assetId",
			"format": "file",
			"file": "http://oursite.com/audio/audiofile.mp3",
			"source": "podcastCMS",
			"intendedDevice": "any",
			"priority": 5
		}
	],
	"template": {
		"productType": "preroll"
	},
	"campaign": {
		"properties": {
			"targeting": {
				"products": [
					{
						"id": "podcastShowX",
						"name": "The Podcast Show",
						"parent": "",
						"status": "active",
						"shareOfVoice": 25,
						"geotargeting": [
							"US"
						],
						"startDate": "1529696444539",
						"endDate": "1539696444539",
						"slots": [
							{
								"_id": "audioPreroll",
								"name": "Audio Preroll",
								"size": "30s",
								"priority": 2
							},
							{
								"_id": "audioPostroll",
								"name": "Audio Post",
								"size": "30s",
								"priority": 5
							}
						]
					}
				],
				"keywords": [
					"DMV",
					"Driving"
				],
				"commercialNode": "news",
				"exclusions": {
					"keywords": [
						"amtrak"
					],
					"articleIds": [],
					"urls": [
						"http://yoursite.com/a-disaster-article"
					]
				},
				"priority": 20
			}
		}
	}
}
